// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#include "Assets\Compute\NoiseInclude.compute"

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
int RandOffset;
RWTexture2D<float4> RenderTex;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    RenderTex[id.xy] = snoise(float3(id.x,id.y,RandOffset));
}
